title: DEP Data Hub
description: Data Engineering Pilipinas (DEP) Data Hub - A community-driven platform for data projects and sources in the Philippines
theme: minima

include:
  - "*.md"
  - "**/*.md"

header_pages:
  - OVERVIEW.md
  - CONTRIBUTING.md
  - ROADMAP.md

plugins:
  - jekyll-seo-tag

author: Data Engineering Pilipinas
twitter:
  username: DEPilipinas
  card: summary
social:
  name: Data Engineering Pilipinas
  links:
    - https://twitter.com/DEPilipinas
    - https://github.com/dataengineeringpilipinas/datahub
    - https://dataengineering.ph
