title: DEP Data Hub
description: The official documentation and resources for the Data Engineering Pilipinas Data Hub.
theme: minima
exclude:
  - README.md
  - project-template.md
  - data-source-template.md
  - contributing.md

# Optional: Manually configure the navigation to avoid auto-including all files
nav:
  - title: "Home"
    url: "/index.html"
  - title: "Projects"
    url: "/docs/index.md#projects"
  - title: "Data Sources"
    url: "/docs/index.md#data-sources"
  - title: "Contribution Guide"
    url: "/docs/contributing.md"
